## Forward Propagation

Import Library

In [ ]:
import numpy as np

Creating input data and output labels (basically AND operation)

In [ ]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np. array([[0,0,0,1]]).T

In [ ]:
X.shape, Y.shape

((4, 2), (4, 1))

Compute the sigmoid function

In [ ]:
def sig(z):
  return (1/ (1 + np.exp(-z)))

Compute the derivation of sigmoid function

In [ ]:
def derivation_sig(z):
  return sig(z) * (1 - sig(z))

Initializing Weights and Biases

In [ ]:
# Initializing weights and biases for the neural network's single neuron(No hidden layer)
# Weights are randomly initialized between -1 and 1


weights = 2 * np.random.random((2,1)) - 1
bias = 2 * np.random.random((1)) - 1
lr = 0.1

print("Initialized Weights:\n", weights)
print("Initialized Bias:\n", bias)

Initialized Weights:
 [[0.77305843]
 [0.01937123]]
Initialized Bias:
 [0.45052166]


In [ ]:
# Forward propagation and weight updates for a single-neuron neural network(No hidden layer)
# Here we don't have any hidden layer so effectively our input layer of output is X.

for iter in range(15000):

  output0 = X

  # Output prediction using sigmoid activation
  act_output = sig(np.dot(output0, weights) + bias)

# Error terms calculation

  # first term is (y_true-y_pred)
  first_term = act_output - Y

  # second term is (o/p of j unit)* (1 - o/p of j unit) so, we're using der_sig
  second_term = derivation_sig(act_output)

  first_two = first_term * second_term

# Weight updates using calculated changes
  # changes that we want to apply on weights so we have the dimension of channges as the dimension of weights(2,1)

  changes = np.array([[0.0], [0.0]])

  for i in range(2):
    for j in range(4):
        changes[i][0] += first_two[j][0] * output0[j][i]

  weights = weights - lr * changes

# Bias update
  # Now for bais_change the only part is change that the o/p(output0[j][i]) is 1

  bias_change = 0.0
  for j in range(4):
        bias_change += first_two[j][0] * 1

  bias = bias - lr * bias_change

# Final output prediction using trained weights and bias
final_output = sig(np.dot(X, weights) + bias)

print("Updated Weights:\n", weights)
print("Updated Bias:\n", bias)
print("Final Output Predictions:\n", final_output)
print("Act Output Predictions:\n", act_output)

Updated Weights:
 [[9.41614807]
 [9.41614807]]
Updated Bias:
 [-14.41245428]
Final Output Predictions:
 [[5.50491219e-07]
 [6.71745222e-03]
 [6.71745224e-03]
 [9.88107010e-01]]
Act Output Predictions:
 [[5.50546697e-07]
 [6.71767637e-03]
 [6.71767639e-03]
 [9.88106615e-01]]


In [ ]:
# Forward propagation and weight updates for a single-neuron neural network(No hidden layer)
# Here we don't have any hidden layer so effectively our input layer of output is X.

for iter in range(15000):

  output0 = X

  # Output prediction using sigmoid activation
  act_output = sig(np.dot(output0, weights) + bias)

# Error terms calculation

  # first term is (y_true-y_pred)
  first_term = act_output - Y

  # second term is (o/p of j unit)* (1 - o/p of j unit) so, we're using der_sig
  second_term = derivation_sig(act_output)

  first_two = first_term * second_term

# Weight updates using calculated changes

  # Here instead of for loop we're using matrix mul
  # so, we're doing dot product (dim_output0 is (4,2) and transpose of it is (2,4) and dim_first_two is (4,1) -----> ((2,1))

  changes = np.dot(output0.T, first_two)
  weights = weights - lr * changes

# Bias update
  # Now for bais_change the only part is changing that is o/p(output0[j][i]) which is equal 1 so, we can simply add up the first_two element instead of using for loop


  bias_change = np.sum(first_two)
  bias = bias - lr * bias_change

# Final output prediction using trained weights and bias
final_output = sig(np.dot(X, weights) + bias)

print("Updated Weights:\n", weights)
print("Updated Bias:\n", bias)
print("Final Output Predictions:\n", final_output)

Updated Weights:
 [[8.01949595]
 [8.01949586]]
Updated Bias:
 [-12.31741562]
Final Output Predictions:
 [[4.47313930e-06]
 [1.34144208e-02]
 [1.34144221e-02]
 [9.76375806e-01]]


**Conclusion:**

A simple implementation of training a single-neuron neural network(No hidden layer) using forward propagation and gradient descent. This approach is suitable for solving binary classification problems where the output can be either 0 or 1.

array([[0.37639952],
       [0.36453838],
       [0.38962847],
       [0.38014603]])