Import Library

In [ ]:
import numpy as np

Input and Output Data Initialization

In [ ]:
# Define the input data matrix and output data matrix that is actually a XOR function.

X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np. array([[0,1,1,0]]).T

In [ ]:
X.shape, Y.shape

((4, 2), (4, 1))

Calculate the sigmoid activation function.

In [ ]:
def sig(z):
  return (1/ (1 + np.exp(-z)))

Calculate the derivative of the sigmoid activation function.

In [ ]:
def derivation_sig(z):
  return sig(z) * (1 - sig(z))

In [ ]:
#  Suppose we have one input layer(with 2 fea and 1 bais), one hidden layer (with 2 node and on bais node) and one output layer

# Initialize weights and biases for the hidden layer.
hid_weight = 2 * np.random.random((2,2)) - 1
hid_bias = 2 * np.random.random((2)) - 1

# Initialize weights and biases for the output layer.
output_weight = 2 * np.random.random((2,1)) - 1
output_bias = 2 * np.random.random((1,1)) - 1
lr = 0.1

In [ ]:
# Perform forward and backward propagation to train the neural network.


for iter in range(10000):

  # Forward Propagation
  output0 = X
  input_hidden = np.dot(output0, hid_weight) + hid_bias
  output_hid = sig(input_hidden)
  inputforOutputLayer = np.dot(output_hid, output_weight) + output_bias
  act_output = sig(inputforOutputLayer)

# Calculate the error and its gradient for the output layer.
  first_term_op_layer = act_output - Y
  second_term_op_layer = derivation_sig(inputforOutputLayer)
  first_two_op_layer = first_term_op_layer * second_term_op_layer

# Calculate the error and its gradient for the hidden layer.
  first_term_hid_layer = np.dot(first_two_op_layer, output_weight.T)
  second_term_hid_layer = derivation_sig(input_hidden)
  first_two_hid_layer = first_term_hid_layer * second_term_hid_layer

# Calculate weight and bias adjustments for the output layer.
  changes_op_layer = np.dot(output_hid.T, first_two_op_layer)
  changes_op_layer_bias = np.sum(first_two_op_layer, axis=0, keepdims=True)

# Calculate weight and bias adjustments for the hidden layer.
  changes_hid_layer = np.dot(output0.T, first_two_hid_layer)
  changes_hid_layer_bias = np.sum(first_two_hid_layer, axis = 0, keepdims=True)

# Update weights and biases using gradient descent.
  output_weight = output_weight - lr*changes_op_layer
  output_bias = output_bias - lr*changes_op_layer_bias
  hid_weight = hid_weight - lr*changes_hid_layer
  hid_bias = hid_bias - lr*changes_hid_layer_bias


# Perform final predictions after training.
output0 = X
input_hidden = np.dot(output0, hid_weight) + hid_bias
output_hid = sig(input_hidden)
inputforOutputLayer = np.dot(output_hid, output_weight) + output_bias
act_output = sig(inputforOutputLayer)


# Print updated weights, biases, and final predictions.
print("Updated Hidden Layer Weights:\n", hid_weight)
print("Updated Hidden Layer Bias:\n", hid_bias)
print("Updated Output Layer Weights:\n", output_weight)
print("Updated Output Layer Bias:\n", output_bias)
print("Final Output Predictions:\n", act_output)

Updated Hidden Layer Weights:
 [[ 5.03522527 -5.13966857]
 [-5.21294654  4.94755702]]
Updated Hidden Layer Bias:
 [[-2.86629121 -2.81152551]]
Updated Output Layer Weights:
 [[7.24181237]
 [7.26012007]]
Updated Output Layer Bias:
 [[-3.57147279]]
Final Output Predictions:
 [[0.05897514]
 [0.94901555]
 [0.94931286]
 [0.05220239]]


In [ ]:
# Compare Ground Truth Labels with Predicted Output
true_labels = np.array([[0, 1, 1, 0]]).T
print("Ground Truth Labels:")
print(true_labels)

print("Predicted Output:")
print(act_output)

print("The predicted output values have been compared to the ground truth labels to assess the model's accuracy.")


Ground Truth Labels:
[[0]
 [1]
 [1]
 [0]]
Predicted Output:
[[0.05897514]
 [0.94901555]
 [0.94931286]
 [0.05220239]]
The predicted output values have been compared to the ground truth labels to assess the model's accuracy.


**Conclusion:**

In this project, a neural network was developed from scratch, including architecture setup, activation functions, forward and backward propagation. Through 10000 training iterations, the network learned to approximate the target output, demonstrating the fundamental principles of neural network training.